### ISSUE TITLE
[ts] Cannot find module '@mean-expert/model/index'.

### ISSUE THREAD

**Issue by dmastag** [mean-expert-official/fireloop-todo-example#1]
I am getting this problem in the console:
![image](https://cloud.githubusercontent.com/assets/5745805/20027543/91c6a74e-a349-11e6-9a01-4cd99b7e3fcd.png)

But I am seeing the file in the node_modules, sadly can't seem to understand why its not picked up by Typescript

![image](https://cloud.githubusercontent.com/assets/5745805/20027538/6de4dbf2-a349-11e6-824c-818e52279d36.png)

**Comment by dmastag** [comment]
I think its because the typings for @mean-expert model hasn't been made yet.
So I tried to change the todo.ts file to [this gist](https://gist.github.com/dmastag/8e8e22d95c7cb3ef15a4301285bba128) and its working.

**Comment by jonathan-casarrubias** [comment]
Hey @dmastag I got this same issue within the generator fireloop, both places are ok for issueing this.

I just want to connect you both to find out the solution

https://github.com/mean-expert-official/generator-fireloop/issues/4

The strange thing is that here it does find the module within node_modules.

I will try to clone in a different directory from scratch and see if I can replicate

**Comment by jonathan-casarrubias** [comment]
@dmastag I just verified and I was unable to replicate the issue, here it just works... Which is annoying, so... I proactively researched and found this is the right way to publish dependencies with declaration files:

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

I just followed this documentation and published @mean-expert/model with its declaration file and updated this repo, though in my computer still working, I'm not totally sure it will fix the issue. I hope so, but  I'm going kind of blind on this.

so just

``` sh
$ git pull
$ npm install
$ fireloop serve
```

by the way, does the fireloop serve command works for you? it does for me and I tried in other computers at the office but, there is a person saying it wont run for him, would you mind to let me know if it does work for you? thanks

Cheers

**Comment by dmastag** [comment]
Still having the same issue.
![image](https://cloud.githubusercontent.com/assets/5745805/20032001/d8e575c8-a3b3-11e6-9f9c-f32d3c8b3c20.png)

Fireloop serve works, it serves both the app and the api. My concern might be that we would need some kind of guide on how to use this on production.

**Comment by jonathan-casarrubias** [comment]
@dmastag its unfortunate the issue persist I'll try to check in different machines on Monday at the office.

I'm actually writing my next article but I will be unable to release it until this issue is fixed, I believe the faster work around is the one the is stated in the other github issue by using:

``` js
../../node_modules/@mean-expert/model/index
```

Could you confirm this works for you?

Regarding the fireloop serve, currently is more for development purposes, while we reach the Release Candidate versions I will be publishing the documentation for serving in production.

But... Truth is that within your webapp, there is a **standard angular cli project**... So, any valid angular-cli command is valid within your webapps.

Same will be for nativescript and ionic, the way these are connected is through the .yo-rc file, take a look on it.

For the loopback part, since now it runs with FireLoop models it needs to be executed using ts-node, but that is already being done within the server.js file, you don't need to worry, so technically to run your server in production can be done with pm2 or any tool as you currently do with loopback just by pointing to server/server.js.

What is missing is the Angular Universal part being served by loopback. But I believe you are more into the Ionic thing.

Anyway, this is still in early stage but I believe in the next couple of months we may reach to RC.

Cheers
Jon.

**Comment by jonathan-casarrubias** [comment]
@dmastag I think this issue is fixed now, I changed several things and proved in diff machines including windows and does work. 

Cheers
Jon
