### ISSUE TITLE
use typescript in server

### ISSUE THREAD

**Issue by heralight** [mean-expert-official/fireloop-todo-example#4]
Hi!

It's a good starting point, but can we migrate server side to typescript with something up to date like https://github.com/jeremysik/loopback-typescript ?

**Comment by jonathan-casarrubias** [comment]
Hi @heralight, for server side, you mean whatever is inside the server directory? because the models already are in typescript and also are from server side, but I guess I understand what you are saying.

If it is whatever it is inside the server directory, then you should know that I have already implemented bootscripts in typescript as follows:

``` js
import { BootScript } from '@mean-expert/boot-script';

@BootScript()
class Authentication {
    constructor(app: any) {
        app.enableAuth();
    }
}
```

and I even added a test suit for the typescript models, but I still don't publish that, I'm preparing everything to launch FireLoop 1 beta and SDK Builder 2.1 rc at with angular universal support at the same time, so that is why I still don't publish it, but I'm really close is just matter of days.

**Comment by heralight** [comment]
Good news! If you need a beta tester... I'm in.

**Comment by jonathan-casarrubias** [comment]
@heralight this has been implemented, more decorators are being developed.

I will close this issue for now

Cheers
Jon
